import { SentenceEntityGlobal } from './global-sentences.model';

export const defaultSentences: SentenceEntityGlobal[] = [
  {
    verb: 'wake up',
    sentence: `Every morning I {verb} at 8 o'clock.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wake up',
    sentence: `My mother {verb} every morning at 6 am.`,
    rightAnswer: 'Present',
    specialForm: 'wakes up',
  },
  {
    verb: 'wake up',
    sentence: `Yesterday Jill {verb} at 10 am, so she was late for school.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'wake up',
    sentence: ` John goes to bed very late every night, so he doesn't {verb} before 9 am.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wake up',
    sentence: `Oliver has {verb} already, so you can call him.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'win',
    sentence: `He isn't very lucky; he has never {verb} a prize in the lottery.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'win',
    sentence: `He never {verb} any tennis games.`,
    rightAnswer: 'Present',
    specialForm: 'wins',
  },
  {
    verb: 'win',
    sentence: `When my brother doesn't {verb} at Monopoly, he gets really angry.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'win',
    sentence: `Last week their club {verb} against the number 1 in the league.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'arise',
    sentence: `Many traffic accidents {verb} from carelessness.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'arise',
    sentence: `You should strike as soon as the opportunity {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'arises',
  },
  {
    verb: 'arise',
    sentence: `The question {verb} as to who should become the new leader.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'arise',
    sentence: ` Political issues might {verb} between these two countries.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'arise',
    sentence: `The problem has {verb} simply because they didn't follow the teacher's instructions.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'awake',
    sentence: `I always {verb} a few times a night.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'awake',
    sentence: `The baby {verb} every three hours.`,
    rightAnswer: 'Present',
    specialForm: 'awakes',
  },
  {
    verb: 'awake',
    sentence: `The loud noise in the street {verb} us early this morning.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'awake',
    sentence: `Please don't {verb} the dog.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'awake',
    sentence: `The news about possible life on Mars has {verb} the interest of many investors.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'be',
    sentence: `My name {verb} Anne, I {verb} a 36-year-old woman.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'be',
    sentence: `Her father {verb} a very successful engineer.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'be',
    sentence: `We {verb} at the cinema when the alarm went off.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'be',
    sentence: `Their daughter {verb} at home, since she had called in sick that day.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'be',
    sentence: `There has to {verb} another option.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'be',
    sentence: `Have you ever {verb} to the United States of America?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bear',
    sentence: `I think nobody understands the cross I {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bear',
    sentence: `The president {verb} full responsibility for the political catastrophe.`,
    rightAnswer: 'Present',
    specialForm: 'bears',
  },
  {
    verb: 'bear',
    sentence: `When the tornado struck, they {verb} it with resilience and faith .`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bear',
    sentence: `I can't {verb} the disgusting smell of cigarettes.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bear',
    sentence: `He has {verb} all his problems with great courage.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'beat',
    sentence: `Every week I {verb} the carpet to get all the dust out.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'beat',
    sentence: `My sister always {verb} me at chess.`,
    rightAnswer: 'Present',
    specialForm: 'beats',
  },
  {
    verb: 'beat',
    sentence: `John {verb} the drum at a slow tempo.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'beat',
    sentence: ` If you can't {verb} them, join them.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'beat',
    sentence: `The victim has been {verb} to death with a golf club.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'become',
    sentence: `You {verb} wiser with age.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'become',
    sentence: `Tim never {verb} angry when he loses a game.`,
    rightAnswer: 'Present',
    specialForm: 'becomes',
  },
  {
    verb: 'become',
    sentence: `We {verb} friends when we met in Paris last year.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'become',
    sentence: `When I'm older, I want to {verb} a teacher.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'become',
    sentence: `China has {verb} a powerful nation.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'begin',
    sentence: `The kids always {verb} doing their homework as soon they get home.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'begin',
    sentence: `The new course {verb} in September.`,
    rightAnswer: 'Present',
    specialForm: 'begins',
  },
  {
    verb: 'begin',
    sentence: `It {verb} to rain heavily when we got to the beach.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'begin',
    sentence: `The meeting needs to {verb} as soon as possible.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'begin',
    sentence: `My uncle has just {verb} looking for another job.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bend',
    sentence: `When I {verb} my arm, it hurts a lot.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bend',
    sentence: `The tree {verb} in the wind.`,
    rightAnswer: 'Present',
    specialForm: 'bends',
  },
  {
    verb: 'bend',
    sentence: `My father {verb} his knees to sit down on the floor.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bend',
    sentence: `You have to be very strong to {verb} an iron bar.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bend',
    sentence: `Lead is easily {verb}.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bet',
    sentence: `I {verb} you didn't know he was my uncle.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bet',
    sentence: `My grandpa {verb} on horses.`,
    rightAnswer: 'Present',
    specialForm: 'bets',
  },
  {
    verb: 'bet',
    sentence: `Last week my grandpa {verb} €250 on the race.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bet',
    sentence: `Are you sure about that? I wouldn't {verb} on it if I were you.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bet',
    sentence: `I have never {verb} on a game before. I think it's a waste of money.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bid',
    sentence: `I {verb} €35 for that old chair.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bid',
    sentence: `She {verb} €100 for that antique table.`,
    rightAnswer: 'Present',
    specialForm: 'bids',
  },
  {
    verb: 'bid',
    sentence: `My dad {verb} €20 for that second-hand bike.`,
    rightAnswer: 'Past',
  },
  {
    verb:
      'On this auction page, it shows how many people have {verb} in the last 5 years.',
    sentence: `{verb} .`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bind',
    sentence: `The guards {verb} the prisoner´s hand and feet.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bind',
    sentence: `She {verb} the ends of the cord together with thread.`,
    rightAnswer: 'Present',
    specialForm: 'binds',
  },
  {
    verb: 'bind',
    sentence: `The ties that {verb} them together were loosening, which made them decide to get a divorce.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bind',
    sentence: `You are {verb} by oath to tell the truth.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bite',
    sentence: `Barking dogs never {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bite',
    sentence: `Tim {verb} his nails; that's the only bad habit he has.`,
    rightAnswer: 'Present',
    specialForm: 'bits',
  },
  {
    verb: 'bite',
    sentence: `The dog {verb} him in the leg three days ago.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bite',
    sentence: `I was {verb} by a mosquito last night.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bleed',
    sentence: `Paper cuts generally {verb} and hurt quite a bit.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bleed',
    sentence: `A paper cut usually {verb} a lot.`,
    rightAnswer: 'Present',
    specialForm: 'bleeds',
  },
  {
    verb: 'bleed',
    sentence: `Sadly the victim {verb} to death of his injuries.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bleed',
    sentence: `Many soldiers have fought and {verb} for their country.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'blow',
    sentence: `First you make a wish and then you {verb} out the candles on the cake.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'blow',
    sentence: `The wind {verb} fiercely.`,
    rightAnswer: 'Present',
    specialForm: 'blows',
  },
  {
    verb: 'blow',
    sentence: `She {verb} her nose in a tissue and washed her hands.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'blow',
    sentence: `I have {verb} up 60 balloons for my dad's birthday.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'break',
    sentence: `Twigs easily {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'break',
    sentence: `He's a rough kid; he always {verb} all his toys.`,
    rightAnswer: 'Present',
    specialForm: 'breaks',
  },
  {
    verb: 'break',
    sentence: `Last night our car {verb} down.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'break',
    sentence: `When they came back home, they found the window had been {verb}.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'breed',
    sentence: `Most birds {verb} in Spring.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'breed',
    sentence: `My grandma {verb} tropical flowers in her little greenhouse.`,
    rightAnswer: 'Present',
    specialForm: 'breeds',
  },
  {
    verb: 'breed',
    sentence: `When I was young, they {verb} fish in that reservoir, but now it's all empty.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'breed',
    sentence: `John has been {verb} to be a gentleman.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'bring',
    sentence: `They always {verb} gifts when they come to visit us.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'bring',
    sentence: `Little Red Riding Hood {verb} her grandma a basket of fruit.`,
    rightAnswer: 'Present',
    specialForm: 'brings',
  },
  {
    verb: 'bring',
    sentence: `He {verb} back several souvenirs from Paris.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'bring',
    sentence: `The postman has {verb} us the mail.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'build',
    sentence: `Birds {verb} their nests in March.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'build',
    sentence: `Breaking up is hard, but they say it {verb} character.`,
    rightAnswer: 'Present',
    specialForm: 'builds',
  },
  {
    verb: 'build',
    sentence: `A famous architect {verb} this castle 20 years ago.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'build',
    sentence: `The office was {verb} in 1975.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'burn',
    sentence: `In winter they {verb} wood in the fireplace .`,
    rightAnswer: 'Present',
  },
  {
    verb: 'burn',
    sentence: `My dad always {verb} everything when he's cooking.`,
    rightAnswer: 'Present',
    specialForm: 'burns',
  },
  {
    verb: 'burn',
    sentence: `I {verb} my finger on a hot frying pan yesterday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'burn',
    sentence: `The forrest was {verb} to the ground due to the wildfire.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'burst',
    sentence: `Balloons {verb} when you blow them up too hard.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'burst',
    sentence: `He {verb} out laughing every time he watches that show.`,
    rightAnswer: 'Present',
    specialForm: 'bursts',
  },
  {
    verb: 'burst',
    sentence: `My mother {verb} into tears when she saw me at the airport.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'burst',
    sentence: `The door was {verb} open to rescue the family from the fire.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'buy',
    sentence: `My aunt and uncle often {verb} eggs, milk and butter at the farm.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'buy',
    sentence: `My sister never {verb} candy, because she's always on a diet.`,
    rightAnswer: 'Present',
    specialForm: 'buys',
  },
  {
    verb: 'buy',
    sentence: `We {verb} this house 5 years ago.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'buy',
    sentence: `The apartment has been {verb} by a French family.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'cast',
    sentence: `They {verb} their lines into the lake, hoping to catch some fish.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'cast',
    sentence: `He secretly {verb} an eye in the girl's direction.`,
    rightAnswer: 'Present',
    specialForm: 'casts',
  },
  {
    verb: 'cast',
    sentence: `The wicked witch {verb} a spell on the frog.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'cast',
    sentence: `The dice have been {verb}.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'catch',
    sentence: `First you {verb} the ball and then you throw it to someone else.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'catch',
    sentence: `Our cat always {verb} mice and frogs.`,
    rightAnswer: 'Present',
    specialForm: 'catches',
  },
  {
    verb: 'catch',
    sentence: `We {verb} the bus to go to the city center last night.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'catch',
    sentence: `The fly was {verb} in the spiderweb.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'choose',
    sentence: `We {verb} a different restaurant for lunch every weekend.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'choose',
    sentence: `His brother usually {verb} chocolate icecream for dessert.`,
    rightAnswer: 'Present',
    specialForm: 'chooses',
  },
  {
    verb: 'choose',
    sentence: `This morning I {verb} to wear my blue sneakers.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'choose',
    sentence: `The chairperson had been {verb} by the board of directors.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'cling',
    sentence: `Young children often {verb} to their parents.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'cling',
    sentence: `The baby {verb} to his daddy's arm.`,
    rightAnswer: 'Present',
    specialForm: 'clings',
  },
  {
    verb: 'cling',
    sentence: `My wet clothes {verb} to my body after walking in the rain for hours.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'cling',
    sentence: ` We have {verb} to the hope of being rescued.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'come',
    sentence: `People from all around {verb} to see the huge Christmas tree at the main square every year.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'come',
    sentence: `His dad {verb} home very late every night.`,
    rightAnswer: 'Present',
    specialForm: 'comes',
  },
  {
    verb: 'come',
    sentence: `My niece {verb} to visit me last summer.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'come',
    sentence: `You have {verb} at the right time.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'cost',
    sentence: `At the local market, twelve bottles of wine {verb} €86.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'cost',
    sentence: `That piece of furniture {verb} €150.`,
    rightAnswer: 'Present',
    specialForm: 'costs',
  },
  {
    verb: 'cost',
    sentence: `This jacket {verb} me €200.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'cost',
    sentence: `It has {verb} him years to build this house.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'creep',
    sentence: `Mistakes easily {verb} in when you're tired.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'creep',
    sentence: `The boy quietly {verb} up the stairs, careful not to awake his parents.`,
    rightAnswer: 'Present',
    specialForm: 'creeps',
  },
  {
    verb: 'creep',
    sentence: `The teacher was so embarrassed that red {verb} up his face.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'creep',
    sentence: `Some errors have {verb} into the text; can you correct them, please?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'cut',
    sentence: `These new knives {verb} very well.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'cut',
    sentence: `The hairdresser {verb} my hair every other month.`,
    rightAnswer: 'Present',
    specialForm: 'cuts',
  },
  {
    verb: 'cut',
    sentence: `Boris {verb} his leg when he was cleaning out the garage.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'cut',
    sentence: `I have {verb} my hand on some glass, can you get me a bandaid please?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'deal',
    sentence: `Teachers {verb} with all kinds of issues these days.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'deal',
    sentence: `As a police officer, her dad {verb} with public offenders all the time.`,
    rightAnswer: 'Present',
    specialForm: 'deals',
  },
  {
    verb: 'deal',
    sentence: `Frank {verb} the cards so we could start playing the game.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'deal',
    sentence: `He was {verb} a bad hand in life.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'dig',
    sentence: `Every summer German tourists {verb} holes all over the Dutch beaches.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'dig',
    sentence: `The archeologist {verb} carefully around the treasure.`,
    rightAnswer: 'Present',
    specialForm: 'digs',
  },
  {
    verb: 'dig',
    sentence: `The dog {verb} a deep hole in the garden.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'dig',
    sentence: `He has {verb} his own grave, always showing up late for work.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'do',
    sentence: `I {verb} my homework every afternoon.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'do',
    sentence: `My brother always {verb} the dishes on Wednesdays and Fridays.`,
    rightAnswer: 'Present',
    specialForm: 'does',
  },
  {
    verb: 'do',
    sentence: `My mother {verb} the laundry yesterday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'do',
    sentence: `Have you ever {verb} that before?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'draw',
    sentence: `First {verb} a circle and then add some lines.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'draw',
    sentence: `The girl {verb} flowers on her notebook.`,
    rightAnswer: 'Present',
    specialForm: 'draws',
  },
  {
    verb: 'draw',
    sentence: `They {verb} pictures on the wall.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'draw',
    sentence: `Pictures have been {verb} on all the school desks.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'dream',
    sentence: `Kids sometimes {verb} about scary monsters under their bed.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'dream',
    sentence: `My father says he never {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'dreams',
  },
  {
    verb: 'dream',
    sentence: `Last night I {verb} that I was flying.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'dream',
    sentence: `He had always {verb} of becoming a famous singer.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'drink',
    sentence: `We always {verb} water at lunch and dinner.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'drink',
    sentence: `My grandma usually {verb} a glass of red wine.`,
    rightAnswer: 'Present',
    specialForm: 'drinks',
  },
  {
    verb: 'drink',
    sentence: `They {verb} too much so they had to call a taxi to take them home.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'drink',
    sentence: `I have never {verb} so much coffee before. I probably won't be able to sleep tonight.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'drive',
    sentence: `You {verb} a car, but you ride a bike.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'drive',
    sentence: `My sister {verb} very badly.`,
    rightAnswer: 'Present',
    specialForm: 'drives',
  },
  {
    verb: 'drive',
    sentence: `The bus driver {verb} the bus to the car park.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'drive',
    sentence: `We have {verb} here all the way from France.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'eat',
    sentence: `We never {verb} fast food.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'eat',
    sentence: `My brother always {verb} fruit for breakfast.`,
    rightAnswer: 'Present',
    specialForm: 'eats',
  },
  {
    verb: 'eat',
    sentence: `They {verb} at a Japanese restaurant last night.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'eat',
    sentence: `This is the best hamburger I've {verb} in my life.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'fall',
    sentence: `In autumn leaves {verb} from the trees.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'fall',
    sentence: `She {verb} in love with every boy she meets.`,
    rightAnswer: 'Present',
    specialForm: 'falls',
  },
  {
    verb: 'fall',
    sentence: `My grandpa {verb} and broke his hip last Thursday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'fall',
    sentence: `I have {verb} for his tricks so many times.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'feed',
    sentence: `The zookeepers {verb} the lions.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'feed',
    sentence: `My aunt always {verb} the neighbors' cat when they're on holiday.`,
    rightAnswer: 'Present',
    specialForm: 'feeds',
  },
  {
    verb: 'feed',
    sentence: `She {verb} the baby before she went to bed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'feed',
    sentence: `Have you {verb} the dogs yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'feel',
    sentence: `I {verb} sad every time I say goodbye to my family.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'feel',
    sentence: `She {verb} happy whenever she sees the ocean.`,
    rightAnswer: 'Present',
    specialForm: 'feels',
  },
  {
    verb: 'feel',
    sentence: `Last night I {verb} sick, so I skipped dinner.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'feel',
    sentence: `I've been going to the gym for 6 months now, and I have never {verb} better.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'fight',
    sentence: `All siblings {verb} every now and then.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'fight',
    sentence: `The knight {verb} the dragon and rescues the princess.`,
    rightAnswer: 'Present',
    specialForm: 'fights',
  },
  {
    verb: 'fight',
    sentence: `Soldiers {verb} in the war.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'fight',
    sentence: `They have {verb} in court for months.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'find',
    sentence: `I always {verb} beautiful shells at the beach.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'find',
    sentence: `She never {verb} her keys; she always leaves them lying around everywhere.`,
    rightAnswer: 'Present',
    specialForm: 'finds',
  },
  {
    verb: 'find',
    sentence: `We {verb} a mysterious shiny rock in our garden yesterday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'find',
    sentence: `They have finally {verb} a cure for this disease.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'flee',
    sentence: `Every summer, people from Sevilla {verb} to the coast to escape the heat.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'flee',
    sentence: `Wherever he {verb}, he will always remember the terrible things he has done.`,
    rightAnswer: 'Present',
    specialForm: 'flees',
  },
  {
    verb: 'flee',
    sentence: `When the thief saw the policeman, he {verb}.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'flee',
    sentence: `We have {verb} the city for fear of the hurricane.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'fly',
    sentence: `Birds {verb} high in the sky.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'fly',
    sentence: `Time {verb} when you're having fun.`,
    rightAnswer: 'Present',
    specialForm: 'flies',
  },
  {
    verb: 'fly',
    sentence: `George {verb} a kite at the beach last week.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'fly',
    sentence: `Her brother is scared of heights, so he has never {verb} before.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'forbid',
    sentence: `I {verb} you to smoke.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'forbid',
    sentence: `The law {verb} stores to sell liquor to minors.`,
    rightAnswer: 'Present',
    specialForm: 'forbids',
  },
  {
    verb: 'forbid',
    sentence: `Her parents {verb} her to see her boyfriend again.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'forbid',
    sentence: `It's {verb} to park here.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'forget',
    sentence: `Every time I {verb} to lock the door.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'forget',
    sentence: `She always {verb} to water the plants.`,
    rightAnswer: 'Present',
    specialForm: 'forgets',
  },
  {
    verb: 'forget',
    sentence: `They {verb} to close the windows.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'forget',
    sentence: `They must have {verb} all about their promise.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'forgive',
    sentence: `People {verb} and forget.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'forgive',
    sentence: `He {verb} her for ruining his birthday.`,
    rightAnswer: 'Present',
    specialForm: 'forgives',
  },
  {
    verb: 'forgive',
    sentence: `She {verb} him for destroying the car.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'forgive',
    sentence: `She hasn't {verb} him for cheating on her.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'freeze',
    sentence: `My grandparents always {verb} all their food.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'freeze',
    sentence: `Every winter when the lake {verb} over we go ice skating.`,
    rightAnswer: 'Present',
    specialForm: 'freeze',
  },
  {
    verb: 'freeze',
    sentence: `Last February, the water pipes {verb} and then they burst.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'freeze',
    sentence: `The water in the basin has {verb} solid.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'get',
    sentence: `You {verb} your baggage at the belts in the arrival hall.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'get',
    sentence: `His girlfriend usually {verb} a taxi to go home late at night.`,
    rightAnswer: 'Present',
    specialForm: 'gets',
  },
  {
    verb: 'get',
    sentence: `I {verb} so many presents for my birthday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'get',
    sentence: `I've {verb} a loan from the bank, so now I'll be able to buy a house.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'give',
    sentence: `They {verb} us presents every Chistmas.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'give',
    sentence: `This old house {verb} me the creeps.`,
    rightAnswer: 'Present',
    specialForm: 'gives',
  },
  {
    verb: 'give',
    sentence: `Julian {verb} me his word that he would help me.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'give',
    sentence: `Thanks, you've {verb} me good advice.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'go',
    sentence: `We {verb} to the fun fair every year.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'go',
    sentence: `My mother-in-law {verb} to the supermarket twice a week.`,
    rightAnswer: 'Present',
    specialForm: 'goes',
  },
  {
    verb: 'go',
    sentence: `The girls {verb} shopping in the mall.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'go',
    sentence: `Jill had already {verb} home when James arrived at the party.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'grind',
    sentence: `They {verb} their coffee by hand every morning.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'grind',
    sentence: `The old woman {verb} wheat into flour every day.`,
    rightAnswer: 'Present',
    specialForm: 'grinds',
  },
  {
    verb: 'grind',
    sentence: `When Alex was young, he {verb} his teeth in his sleep.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'grind',
    sentence: `For this recipe, use finely {verb} corn.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'grow',
    sentence: `Children {verb} up too quickly.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'grow',
    sentence: `Our daughter {verb} so fast.`,
    rightAnswer: 'Present',
    specialForm: 'grows',
  },
  {
    verb: 'grow',
    sentence: `Martin {verb} a beard, which made him look old.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'grow',
    sentence: `Look at you! You've {verb} so tall.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hang',
    sentence: `People usually {verb} their coats in the hallway.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hang',
    sentence: `He {verb} his hat on the peg.`,
    rightAnswer: 'Present',
    specialForm: 'hangs',
  },
  {
    verb: 'hang',
    sentence: `He {verb} his jacket over his chair before he sat down.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hang',
    sentence: `Have you {verb} the towels up to dry?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'have',
    sentence: `They always {verb} a lot of flowers in their garden.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'have',
    sentence: `My boyfriend {verb} long dark hair and blue eyes.`,
    rightAnswer: 'Present',
    specialForm: 'has',
  },
  {
    verb: 'have',
    sentence: `When we were young, we {verb} a lot of pets.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'have',
    sentence: `Has he {verb} any luck finding his keys?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hear',
    sentence: `Every night we {verb} the owl, but we never see it.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hear',
    sentence: `She {verb} voices in her head sometimes.`,
    rightAnswer: 'Present',
    specialForm: 'hears',
  },
  {
    verb: 'hear',
    sentence: `I {verb} John singing in the shower.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hear',
    sentence: `Have you {verb} about the next Harry Potter film coming out?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hide',
    sentence: `I never {verb} anything from my friends.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hide',
    sentence: `The boy {verb} the candy in his pocket.`,
    rightAnswer: 'Present',
    specialForm: 'hides',
  },
  {
    verb: 'hide',
    sentence: `He {verb} the money under his bed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hide',
    sentence: `Where has she {verb} her diary?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hit',
    sentence: `The brothers argue all the time, but never {verb} each other.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hit',
    sentence: `Sander {verb} a homerun almost every game.`,
    rightAnswer: 'Present',
    specialForm: 'hits',
  },
  {
    verb: 'hit',
    sentence: `I couldn't see anything so I {verb} my toes against the edge of the bed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hit',
    sentence: `I got {verb} by a car.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hold',
    sentence: `Can you {verb} my bag for a second please?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hold',
    sentence: `She {verb} her baby tight as she crosses the slippery road. `,
    rightAnswer: 'Present',
    specialForm: 'holds',
  },
  {
    verb: 'hold',
    sentence: `I {verb} her bag when she went to the toilet.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hold',
    sentence: `The terrorist was {verb} down on the floor by 5 police officers.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'hurt',
    sentence: `They say words don't {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'hurt',
    sentence: `It {verb} when you break your arm.`,
    rightAnswer: 'Present',
    specialForm: 'hurts',
  },
  {
    verb: 'hurt',
    sentence: `She fell and {verb} her knee.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'hurt',
    sentence: `He would never have {verb} the child.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'keep',
    sentence: `You {verb} fruit and vegetables in the fridge.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'keep',
    sentence: `She {verb} forgetting her keys.`,
    rightAnswer: 'Present',
    specialForm: 'keeps',
  },
  {
    verb: 'keep',
    sentence: `They {verb} the family secret for a long time.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'keep',
    sentence: `Our old furniture has been {verb} in the garage.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'kneel',
    sentence: `They {verb} down to tie their shoes.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'kneel',
    sentence: `He {verb} down beside her to help the old lady get up again.`,
    rightAnswer: 'Present',
    specialForm: 'kneels',
  },
  {
    verb: 'kneel',
    sentence: `Howard {verb} down to pick up the pieces of broken glass.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'know',
    sentence: `I don't think I {verb} how to find my way out of this maze.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'know',
    sentence: `My friend {verb} how to speak five languages fluently.`,
    rightAnswer: 'Present',
    specialForm: 'knows',
  },
  {
    verb: 'know',
    sentence: `I {verb} you wouldn't give up on me.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'know',
    sentence: `We've {verb} each other since we were in pre-school.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'lay',
    sentence: `I {verb} the baby in the cradle as soon as he sleeps.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lay',
    sentence: `This chicken {verb} 5 eggs every day.`,
    rightAnswer: 'Present',
    specialForm: 'lays',
  },
  {
    verb: 'lay',
    sentence: `The shop assistent {verb} all the clothes on the counter.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'lay',
    sentence: `The chickens haven't {verb} any eggs recently.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'lead',
    sentence: `The parents {verb} the young boy by the hand as they cross the street.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lead',
    sentence: `My uncle {verb} a quiet life; he hardly leaves the house.`,
    rightAnswer: 'Present',
    specialForm: 'leads',
  },
  {
    verb: 'lead',
    sentence: `Chris {verb} the way, while everybody else followed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'lead',
    sentence: `Victor has {verb} the basketball team for 3 years.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'lean',
    sentence: `They always {verb} their elbows on the table while they're eating.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lean',
    sentence: `My grandma always {verb} on my grandpa's arm when they go for a walk.`,
    rightAnswer: 'Present',
    specialForm: 'leans',
  },
  {
    verb: 'lean',
    sentence: `She {verb} over the railing to look all the way down.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'leap',
    sentence: `When the boys {verb} over the stream, they always get their shoes wet.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'leap',
    sentence: `All of a sudden the cat sees a frog and it {verb} in the air.`,
    rightAnswer: 'Present',
    specialForm: 'leaps',
  },
  {
    verb: 'leap',
    sentence: `When the alarm went off, she {verb} out of bed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'learn',
    sentence: `You live, you {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'learn',
    sentence: `She {verb} fast; she's one of the best students of the class.`,
    rightAnswer: 'Present',
    specialForm: 'learns',
  },
  {
    verb: 'learn',
    sentence: `I {verb} a lot at that cooking course last month.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'learn',
    sentence: `Has she {verb} how to tie her shoe laces yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'leave',
    sentence: `Don't {verb} your glasses on the chair; someone might sit on them.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'leave',
    sentence: `The bus {verb} every 20 minutes.`,
    rightAnswer: 'Present',
    specialForm: 'leaves',
  },
  {
    verb: 'leave',
    sentence: `We {verb} the cinema as soon as the film had finished.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'leave',
    sentence: `Oh no! I have {verb} the keys inside the car.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'lend',
    sentence: `Can you {verb} me your bike for just a few days, please?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lend',
    sentence: `Susan always {verb} her classmates all her pencils.`,
    rightAnswer: 'Present',
    specialForm: 'lends',
  },
  {
    verb: 'lend',
    sentence: `He {verb} me two books last year and I still haven't given them back to him.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'let',
    sentence: `{verb} me see that.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'let',
    sentence: `His mother {verb} him play outside until it gets dark.`,
    rightAnswer: 'Present',
    specialForm: 'lets',
  },
  {
    verb: 'let',
    sentence: `When I was young, my parents never {verb} me go to the park alone.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'lie',
    sentence: `On warm summer nights, we {verb} in the grass and watch the stars.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lie',
    sentence: `She always {verb} on the left side of the bed.`,
    rightAnswer: 'Present',
    specialForm: 'lies',
  },
  {
    verb: 'lie',
    sentence: `Last night he {verb} on the bed, but he couldn't fall asleep.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'lie',
    sentence: `He had {verb} in bed for years, before he finally passed away.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'light',
    sentence: `In winter, we always {verb} a fire in the chimney.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'light',
    sentence: `She {verb} a cigarette every 10 minutes; she really smokes too much.`,
    rightAnswer: 'Present',
    specialForm: 'lights',
  },
  {
    verb: 'light',
    sentence: `Last night there was a power cut, so we {verb} some candles.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'light',
    sentence: `You shouldn't leave {verb} candles unattended.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'lose',
    sentence: `You win some, you {verb} some.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'lose',
    sentence: `If he {verb} a game, he always gets really angry.`,
    rightAnswer: 'Present',
    specialForm: 'loses',
  },
  {
    verb: 'lose',
    sentence: `Last week my brother {verb} his wallet.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'lose',
    sentence: `Oh my God! What are you doing? Have you {verb} your mind!?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'make',
    sentence: `We all {verb} mistakes sometimes.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'make',
    sentence: `My mum {verb} apple pie every Sunday.`,
    rightAnswer: 'Present',
    specialForm: 'makes',
  },
  {
    verb: 'make',
    sentence: `Last Saturday my sister {verb} fresh tomato soup.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'make',
    sentence: `These clothes were {verb} in China.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'mean',
    sentence: `I don't understand that. What does it {verb}?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'mean',
    sentence: `What does the word 'portatil' mean? It {verb} 'laptop'.`,
    rightAnswer: 'Present',
    specialForm: 'means',
  },
  {
    verb: 'mean',
    sentence: `He was trying to apologise, but his apologies {verb} nothing to me.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'mean',
    sentence: `Even though she knew he had never {verb} to hurt her, she couldn't forgive him.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'meet',
    sentence: `My cousins and I {verb} once a month to catch up.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'meet',
    sentence: `My niece {verb} her boyfriend at weekends.`,
    rightAnswer: 'Present',
    specialForm: 'meets',
  },
  {
    verb: 'meet',
    sentence: `My parents {verb} when they were in high school. It was love at first sight.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'meet',
    sentence: `Have you ever {verb} a celebrity? `,
    rightAnswer: 'Participle',
  },
  {
    verb: 'overcome',
    sentence: `His family has to {verb} many difficulties.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'overcome',
    sentence: `When he was a child, my friend {verb} many obstacles.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'overcome',
    sentence: `Paul was {verb} by jealousy.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'pay',
    sentence: `If you {verb} for lunch this time, then next time lunch will be on me.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'pay',
    sentence: `When I meet my friend for lunch or dinner, he always {verb} for everything.`,
    rightAnswer: 'Present',
    specialForm: 'pays',
  },
  {
    verb: 'pay',
    sentence: `They {verb} the bill and left the restaurant.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'pay',
    sentence: `Have you {verb} the bill yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'put',
    sentence: `Before going to school, I have a shower, I have breakfast and I {verb} on my clothes.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'put',
    sentence: `At weekends, she always {verb} on a fancy dress and high heels.`,
    rightAnswer: 'Present',
    specialForm: 'puts',
  },
  {
    verb: 'put',
    sentence: `As soon as they came home, they {verb} the icecream in the freezer.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'put',
    sentence: `Have you {verb} the milk in the fridge?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'read',
    sentence: `Kids hardly {verb} books anymore; all they do is watch TV and play videogames.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'read',
    sentence: `My best friend is a bookworm; he {verb} at least 2 books a week.`,
    rightAnswer: 'Present',
    specialForm: 'reads',
  },
  {
    verb: 'read',
    sentence: `The last book I {verb} was Harry Potter and the Philosopher's Stone.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'read',
    sentence: `Has your father {verb} today's newspaper yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'ride',
    sentence: `My grandparents still {verb} their bikes every day.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'ride',
    sentence: `Eugene {verb} his bike as often as he can.`,
    rightAnswer: 'Present',
    specialForm: 'rides',
  },
  {
    verb: 'ride',
    sentence: `As a child, she {verb} her bike all the time.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'ride',
    sentence: `Have you ever {verb} a horse?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'ring',
    sentence: `The church bells {verb} every Sunday morning.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'ring',
    sentence: `My mother {verb} my grandma every night to check if she's ok.`,
    rightAnswer: 'Present',
    specialForm: 'rings',
  },
  {
    verb: 'ring',
    sentence: `Last night, the doorbell {verb} loudly and woke everybody up.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'ring',
    sentence: `Have you {verb} the doctor yet? You should, if you're not feeling well.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'rise',
    sentence: `Good morning, it's time to wake up, {verb} and shine!`,
    rightAnswer: 'Present',
  },
  {
    verb: 'rise',
    sentence: `'The sun {verb} in the east and sets in the west.`,
    rightAnswer: 'Present',
    specialForm: 'rises',
  },
  {
    verb: 'rise',
    sentence: `The temperature {verb} as the sun was getting hotter and hotter.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'rise',
    sentence: `The cost of living has {verb}.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'run',
    sentence: `They {verb} to school every morning; they always wake up late.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'run',
    sentence: `His sister {verb} 10 km every morning.`,
    rightAnswer: 'Present',
    specialForm: 'runs',
  },
  {
    verb: 'run',
    sentence: `Five years ago I {verb} a marathon.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'run',
    sentence: `My friends have never {verb} a race before. They just don't like running.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'saw',
    sentence: `With this blade, you can {verb} wood, metal and other hard materials.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'saw',
    sentence: `The carpenter {verb} a hole in the board.`,
    rightAnswer: 'Present',
    specialForm: 'saws',
  },
  {
    verb: 'saw',
    sentence: `Yesterday my dad {verb} the wooden boards in half.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'saw',
    sentence: `The tops of the wooden pilars are {verb} off.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'say',
    sentence: `My parents always {verb} I have to wash my hands before having lunch.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'say',
    sentence: `Every morning his mother {verb} to him: 'Be a good boy'.`,
    rightAnswer: 'Present',
    specialForm: 'says',
  },
  {
    verb: 'say',
    sentence: `When my grandparents were still alive, they always {verb} life was better when they were young.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'say',
    sentence: `As I have {verb} before, doing your homework is really important`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'see',
    sentence: `My teacher always says: '{verb} you later, alligator!'`,
    rightAnswer: 'Present',
  },
  {
    verb: 'see',
    sentence: `The captain says he always {verb} dolphins when he's at sea.`,
    rightAnswer: 'Present',
    specialForm: 'sees',
  },
  {
    verb: 'see',
    sentence: `When she {verb} her son at the airport, she ran towards him with open arms.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'see',
    sentence: `Have you {verb} the new James Bond film?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'seek',
    sentence: `Let's play hide and {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'seek',
    sentence: `Everyone {verb} happiness.`,
    rightAnswer: 'Present',
    specialForm: 'seeks',
  },
  {
    verb: 'seek',
    sentence: `He {verb} shelter from the rain; it was raining buckets.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'seek',
    sentence: `I don't like my job. I should have {verb} other employment.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sell',
    sentence: `Did you know they {verb} fresh bread at that gas station?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sell',
    sentence: `Susy {verb} sea shells by the seashore.`,
    rightAnswer: 'Present',
    specialForm: 'sells',
  },
  {
    verb: 'sell',
    sentence: `They {verb} the house when they got divorced.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sell',
    sentence: `Has your grandfather {verb} his old motorbike yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'send',
    sentence: `They {verb} us a Christmas card every year.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'send',
    sentence: `Nowadays hardly anyone {verb} postcards anymore.`,
    rightAnswer: 'Present',
    specialForm: 'sends',
  },
  {
    verb: 'send',
    sentence: `The teacher {verb} her students a message to let them know the class was cancelled.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'send',
    sentence: `I have {verb} you a letter. Haven't you received it yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'set',
    sentence: `Get ready, {verb}, go!`,
    rightAnswer: 'Present',
  },
  {
    verb: 'set',
    sentence: `My dad usually {verb} the table while my mum prepares lunch.`,
    rightAnswer: 'Present',
    specialForm: 'sets',
  },
  {
    verb: 'set',
    sentence: `He walked into the kitchen and he {verb} the box of groceries down on the table.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'set',
    sentence: `Have you {verb} the alarm clock?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sew',
    sentence: `She can {verb} very well.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sew',
    sentence: `My aunt {verb} her own clothes.`,
    rightAnswer: 'Present',
    specialForm: 'sews',
  },
  {
    verb: 'sew',
    sentence: `My mum {verb} my ripped jeans by hand.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sew',
    sentence: `Have you ever {verb} on a button?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'shake',
    sentence: `When you meet someone, you {verb} hands.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shake',
    sentence: `She always {verb} the bottle of juice before pouring us a glass.`,
    rightAnswer: 'Present',
    specialForm: 'shakes',
  },
  {
    verb: 'shake',
    sentence: `The whole house {verb} because of the earthquake.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shake',
    sentence: `James Bond likes his martini {verb}, not stirred.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'shear',
    sentence: `They usually {verb} sheep in spring.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shear',
    sentence: `The farmer {verb} his sheep every spring.`,
    rightAnswer: 'Present',
    specialForm: 'shears',
  },
  {
    verb: 'shear',
    sentence: `They {verb} the sheep last week.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shear',
    sentence: `Look at those sheep! The farmer has just {verb} them.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'shine',
    sentence: `I have to {verb} my shoes.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shine',
    sentence: `The sun {verb} brightly in the sky.`,
    rightAnswer: 'Present',
    specialForm: 'shines',
  },
  {
    verb: 'shine',
    sentence: `Last night the moon {verb} brightly.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shoot',
    sentence: `Don't {verb} the messenger.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shoot',
    sentence: `The policemen {verb} the suspect in the leg and captures him.`,
    rightAnswer: 'Present',
    specialForm: 'shoots',
  },
  {
    verb: 'shoot',
    sentence: `The cow was beyond saving, so the cowboy {verb} it to put it out of its misery.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shoot',
    sentence: `Has your father ever {verb} a gun?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'show',
    sentence: `The instructors at the gym always {verb} new clients how to use the fitness equipment.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'show',
    sentence: `She's so proud of her garden; she always {verb} it to everyone.`,
    rightAnswer: 'Present',
    specialForm: 'shows',
  },
  {
    verb: 'show',
    sentence: `This morning, the biology teacher {verb} us how to use the microscope.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'show',
    sentence: `The real estate agent has just {verb} us the house. We love it, so we're going to make an offer.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'shrink',
    sentence: `The older we get, the more we {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shrink',
    sentence: `Don't wash that shirt on a high temperature; cotton easily {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'shrinks',
  },
  {
    verb: 'shrink',
    sentence: `My favourite jeans {verb} when I washed them and now they don't fit anymore.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shrink',
    sentence: `Has this sweater {verb} or have I just grown taller?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'shut',
    sentence: `My parents always {verb} all the windows before leaving the house.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'shut',
    sentence: `He always {verb} the door with a bang. Why can't he just close it more carefully?`,
    rightAnswer: 'Present',
    specialForm: 'shuts',
  },
  {
    verb: 'shut',
    sentence: `The movie was so scary, so I {verb} my eyes and prayed for it to end soon.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'shut',
    sentence: `Are you sure you have {verb} the door?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sing',
    sentence: `In summer, we {verb} songs around the campfire every night.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sing',
    sentence: `Do you know who {verb} that song?`,
    rightAnswer: 'Present',
    specialForm: 'sings',
  },
  {
    verb: 'sing',
    sentence: `Mario played the piano and Lucy {verb} 'happy birthday'.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sing',
    sentence: `That song was {verb} beautifully by the choir. `,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sink',
    sentence: `Nowadays boats hardly ever {verb} anymore.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sink',
    sentence: `Wood floats on water, but iron {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'sinks',
  },
  {
    verb: 'sink',
    sentence: `The Titanic {verb} after it had hit an iceberg.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sink',
    sentence: `Two passenger ships were {verb} during last night's storm.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sit',
    sentence: `Come in and {verb} down, please.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sit',
    sentence: `She always {verb} next to her best friend.`,
    rightAnswer: 'Present',
    specialForm: 'sits',
  },
  {
    verb: 'sit',
    sentence: `Last night we all {verb} by the fireplace, where it was nice and warm.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sleep',
    sentence: `Good night, {verb} tight.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sleep',
    sentence: `My boyfriend always {verb} on the left side of the bed.`,
    rightAnswer: 'Present',
    specialForm: 'sleeps',
  },
  {
    verb: 'sleep',
    sentence: `Last night I hardly {verb} a wink. I'm so tired now.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sleep',
    sentence: `Good morning, have you {verb} well?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'slide',
    sentence: `You have to {verb} to unlock the screen of your phone.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'slide',
    sentence: `The football player {verb} to hit the ball and he scores!`,
    rightAnswer: 'Present',
    specialForm: 'slides',
  },
  {
    verb: 'slide',
    sentence: `Last January all the kids in my neighbourhood {verb} down the snowy hill on their sleds.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'slide',
    sentence: `Have you ever {verb} on a sled in the snow?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'smell',
    sentence: `I {verb} smoke; my brother must have been smoking cigarettes again.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'smell',
    sentence: `Are you baking a cake? It {verb} so good!`,
    rightAnswer: 'Present',
    specialForm: 'smells',
  },
  {
    verb: 'smell',
    sentence: `Last night we {verb} gas, so we checked the whole house before we went to bed.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'smell',
    sentence: `Have you ever {verb} a wet dog? Trust me, it smells horrible.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sow',
    sentence: `You reap what you {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sow',
    sentence: `Every year in March my grandma {verb} flower seeds in her garden.`,
    rightAnswer: 'Present',
    specialForm: 'sows',
  },
  {
    verb: 'sow',
    sentence: `The farmer {verb} his fields with wheat 3 months ago.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sow',
    sentence: `The fields have been {verb} with corn and wheat.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'speak',
    sentence: `{verb} .`,
    rightAnswer: 'Present',
  },
  {
    verb: 'speak',
    sentence: `His daughter {verb} 6 languages: English, Spanish, German, French, Russian and Japanese.`,
    rightAnswer: 'Present',
    specialForm: 'speaks',
  },
  {
    verb: 'speak',
    sentence: `I didn't know his father {verb} Portuguese.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'speak',
    sentence: `Everyone said I had {verb} very well and intelligibly at the presentation.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'speed',
    sentence: `More money is needed to {verb} the development of a safe and effective vaccine.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'speed',
    sentence: `Every half an hour a train {verb} by their house.`,
    rightAnswer: 'Present',
    specialForm: 'speeds',
  },
  {
    verb: 'speed',
    sentence: `A group of kids {verb} past us on their bikes about an hour ago.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spell',
    sentence: `How do you {verb} your last name?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spell',
    sentence: `Tom always {verb} my surname wrong.`,
    rightAnswer: 'Present',
    specialForm: 'spells',
  },
  {
    verb: 'spell',
    sentence: `The lady at the bank {verb} my name wrong.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spell',
    sentence: `How is that word {verb}?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'spend',
    sentence: `We {verb} every summer at my aunt and uncle's house in Italy.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spend',
    sentence: `Each month she {verb} half her salary on clothes and shoes.`,
    rightAnswer: 'Present',
    specialForm: 'spends',
  },
  {
    verb: 'spend',
    sentence: `I {verb} 4 hours doing my homework last night.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spend',
    sentence: `She has {verb} hours at the gym trying to lose weight.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'spill',
    sentence: `Please be careful, don't {verb} ketchup all over your new dress!`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spill',
    sentence: `My father-in-law is so clumsy; he always {verb} food all over the place.`,
    rightAnswer: 'Present',
    specialForm: 'spills',
  },
  {
    verb: 'spill',
    sentence: `Yesterday my dad {verb} coffee on the carpet. Thank goodness my mum was able to clean it.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spill',
    sentence: `It's no use crying over {verb} milk.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'spit',
    sentence: `Football players always {verb} during the game, I think that's gross.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spit',
    sentence: `I can't stand the way he {verb}; it's revolting.`,
    rightAnswer: 'Present',
    specialForm: 'spits',
  },
  {
    verb: 'spit',
    sentence: `She {verb} out her chewing gum and threw it in the bin.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spit',
    sentence: `I have never {verb} on the ground; I'm a lady, you know.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'split',
    sentence: `How about we {verb} the bill and we each pay half?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'split',
    sentence: `The waiter {verb} the bill for the clients.`,
    rightAnswer: 'Present',
    specialForm: 'splits',
  },
  {
    verb: 'split',
    sentence: `When they hit the jackpot last year, they {verb} the money fifty-fifty.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'split',
    sentence: `The money will probably be {verb} evenly between all five of them.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'spoil',
    sentence: `I don't want to {verb} everything, but I'm not feeling well, so I have to cancel our meeting.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spoil',
    sentence: `Their grandma always {verb} them with too many presents and candy.`,
    rightAnswer: 'Present',
    specialForm: 'spoils',
  },
  {
    verb: 'spoil',
    sentence: `He {verb} the whole party with his annoying behaviour.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spoil',
    sentence: `Those kids are {verb}; they always get everything and they are never told 'no'.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'spread',
    sentence: `My cousins always {verb} thick layers of Nutella on their bread.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'spread',
    sentence: `Bad news always {verb} quickly.`,
    rightAnswer: 'Present',
    specialForm: 'spreads',
  },
  {
    verb: 'spread',
    sentence: `The fire {verb} rapidly; the whole house was burnt to the ground in no time.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'spread',
    sentence: `The virus has {verb} exponentially. Strict measures are being taken to control it.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'stand',
    sentence: `I can't {verb} the way he chews. Apparently he has never learnt to eat with his mouth closed.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'stand',
    sentence: `The teacher usually {verb} in the middle of the classroom.`,
    rightAnswer: 'Present',
    specialForm: 'stands',
  },
  {
    verb: 'stand',
    sentence: `Daniel got so angry, that he {verb} up and left the meeting.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'stand',
    sentence: `Have you ever {verb} on the top of the Eiffel Tower?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'steal',
    sentence: `It's wrong to {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'steal',
    sentence: `His friend sometimes {verb} candy from the supermarket.`,
    rightAnswer: 'Present',
    specialForm: 'steals',
  },
  {
    verb: 'steal',
    sentence: `Someone {verb} my purse this morning.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'steal',
    sentence: `My bike was {verb} last Wednesday.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'stick',
    sentence: `Wet clothes {verb} to your skin.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'stick',
    sentence: `She {verb} a stamp on the envelope and throws it in the mailbox.`,
    rightAnswer: 'Present',
    specialForm: 'sticks',
  },
  {
    verb: 'stick',
    sentence: `My grandparents had a good marriage; they {verb} together through thick and thin.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'stick',
    sentence: `The kids will be {verb} to the TV all afternoon.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sting',
    sentence: `Bees will die after they {verb}.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sting',
    sentence: `There's shampoo in my eyes and it {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'stings',
  },
  {
    verb: 'sting',
    sentence: `When I went for a swim this morning, the seawater {verb} my wound.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sting',
    sentence: `I was {verb} by a mosquito last night.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'stink',
    sentence: `Your shoes {verb}. I think you have stepped in some dog poo.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'stink',
    sentence: `Oh my god, it {verb} in here! Can somebody please open a window?`,
    rightAnswer: 'Present',
    specialForm: 'stinks',
  },
  {
    verb: 'stink',
    sentence: `The whole house {verb} because my uncle had been smoking cigars all night.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'strike',
    sentence: `I {verb} a match to light the candles for our romantic dinner.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'strike',
    sentence: `You have to be back home before the clock {verb} 11.`,
    rightAnswer: 'Present',
    specialForm: 'strikes',
  },
  {
    verb: 'strike',
    sentence: `Last night, lightning {verb} the tower and it was destroyed completely.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'strike',
    sentence: `Joe is in the hospital; he was {verb} by lightning.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'strive',
    sentence: `If you {verb} for excellence, then I'm sure you'll be successful.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'strive',
    sentence: `She {verb} hard at school to get excellent marks.`,
    rightAnswer: 'Present',
    specialForm: 'strives',
  },
  {
    verb: 'strive',
    sentence: `She has finally reached the goal for which she {verb} so bravely.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'strive',
    sentence: `We have {verb} to eliminate starvation in Africa.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'swear',
    sentence: `I {verb} I'm telling the truth.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'swear',
    sentence: `She {verb} she'll go to the doctor tomorrow.`,
    rightAnswer: 'Present',
    specialForm: 'swears',
  },
  {
    verb: 'swear',
    sentence: `I {verb} to myself I would never talk to him ever again.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'swear',
    sentence: `She could have {verb} she locked the door, but apparently she hadn't.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'sweep',
    sentence: `All you have to do is {verb} the floor.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'sweep',
    sentence: `The cleaning lady {verb} the floor every morning.`,
    rightAnswer: 'Present',
    specialForm: 'sweeps',
  },
  {
    verb: 'sweep',
    sentence: `I {verb} the floor just an hour ago and now it's all dirty again!`,
    rightAnswer: 'Past',
  },
  {
    verb: 'sweep',
    sentence: `Has she {verb} the house yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'swim',
    sentence: `Can you {verb}?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'swim',
    sentence: `She {verb} in the sea every day of the year.`,
    rightAnswer: 'Present',
    specialForm: 'swims',
  },
  {
    verb: 'swim',
    sentence: `She jumped into the pool and {verb} 20 laps.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'swim',
    sentence: `Scientists don't know the whale has {verb} to the shore.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'swing',
    sentence: `You are never too old to {verb} on a swing.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'swing',
    sentence: `The psychiatric patient suddenly {verb} from one mood to another.`,
    rightAnswer: 'Present',
    specialForm: 'swings',
  },
  {
    verb: 'swing',
    sentence: `He {verb} his leg over the fence and jumped into the neighbor's garden.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'take',
    sentence: `You can {verb} a bus to the city center.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'take',
    sentence: `She {verb} a deep breath before jumping into the ice cold lake.`,
    rightAnswer: 'Present',
    specialForm: 'takes',
  },
  {
    verb: 'take',
    sentence: `My grandpa {verb} my grandma's hand and told her that he loved her.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'take',
    sentence: `Has the patient {verb} his medicine yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'teach',
    sentence: `I {verb} English at an academy.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'teach',
    sentence: `Sandra {verb} Physical Education at a secondary school.`,
    rightAnswer: 'Present',
    specialForm: 'teaches',
  },
  {
    verb: 'teach',
    sentence: `My grandma {verb} me how to knit.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'teach',
    sentence: `The kids have been {verb} to stand up when the teacher enters the classroom.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'tear',
    sentence: `Everybody, {verb} a piece of paper in two and fold both halves.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'tear',
    sentence: `The boy falls from the tree and {verb} his t-shirt on a branch.`,
    rightAnswer: 'Present',
    specialForm: 'tears',
  },
  {
    verb: 'tear',
    sentence: `My brother accidentally {verb} a hole in his jeans while playing in the garden.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'tear',
    sentence: `The letter was {verb} to pieces; it was impossible to read it.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'tell',
    sentence: `So {verb} me, how was your romantic weekend in Paris?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'tell',
    sentence: `My sister always {verb} me everything; she doesn't keep any secrets from me.`,
    rightAnswer: 'Present',
    specialForm: 'tells',
  },
  {
    verb: 'tell',
    sentence: `I {verb} you that wasn't a good idea!`,
    rightAnswer: 'Past',
  },
  {
    verb: 'tell',
    sentence: `Have I {verb} you lately that I love you?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'think',
    sentence: `I {verb} today will be a good day to go to the beach.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'think',
    sentence: `Her husband {verb} he's always right.`,
    rightAnswer: 'Present',
    specialForm: 'thinks',
  },
  {
    verb: 'think',
    sentence: `They {verb} about going on holiday to Germany, but in the end they went to Frannce.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'think',
    sentence: `Have you ever {verb} about moving abroad?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'throw',
    sentence: `Don't {verb} in the towel. You shouldn't give up hope just yet.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'throw',
    sentence: `Tom {verb} Mary the ball, but she fails to catch it.`,
    rightAnswer: 'Present',
    specialForm: 'throws',
  },
  {
    verb: 'throw',
    sentence: `The boy got angry and {verb} his toy in the corner.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'throw',
    sentence: `Have you {verb} away the trash yet?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'tread',
    sentence: `In the public park it's not allowed to {verb} on the grass.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'tread',
    sentence: `He {verb} in his father's footsteps; he is a butcher, like his dad.`,
    rightAnswer: 'Present',
    specialForm: 'treads',
  },
  {
    verb: 'tread',
    sentence: `He accidentally {verb} on her foot last Friday.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'tread',
    sentence: `This narrow and steep path up the mountain has never been {verb} before.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'undergo',
    sentence: `The planes have to {verb} rigorous safety checks at least once a month.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'undergo',
    sentence: `The protagonist {verb} a sequence of changes throughout the story.`,
    rightAnswer: 'Present',
    specialForm: 'undergoes',
  },
  {
    verb: 'undergo',
    sentence: `The cruiseship successfully {verb} the trials in coastal waters in, so this morning it was launched with a huge ceremony.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'undergo',
    sentence: `Most old paintings at the museum have {verb} extensive restoration.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'understand',
    sentence: `Do you {verb} what I'm trying to say?`,
    rightAnswer: 'Present',
  },
  {
    verb: 'understand',
    sentence: `She {verb} her friend better than anyone.`,
    rightAnswer: 'Present',
    specialForm: 'understands',
  },
  {
    verb: 'understand',
    sentence: `My teacher had been explaining it to me for weeks before I finally {verb}.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'understand',
    sentence: `I have never {verb} why they decided to leave the country.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'upset',
    sentence: `I'm sorry, I didn't mean to {verb} you.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'upset',
    sentence: `It {verb} me when you raise your voice like that.`,
    rightAnswer: 'Present',
    specialForm: 'upsets',
  },
  {
    verb: 'upset',
    sentence: `Talking about his troubled childhood {verb} him, so he changed the subject.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'upset',
    sentence: `Has he {verb} you with his insulting joke?`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'wake up',
    sentence: `You are only able to remember dreams if you {verb} in the middle of them.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wake up',
    sentence: `There's no hurry, I'll wait until he {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'wakes up',
  },
  {
    verb: 'wake up',
    sentence: `I was having a nightmare until all of a sudden I {verb}.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'wake up',
    sentence: `I have just {verb} with a terrrible hangover. I really shouldn't drink so much wine anymore.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'wear',
    sentence: `You should {verb} a scarf, it's getting chilly outside.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wear',
    sentence: `My brother {verb} his heart on his sleeve, he's one of the most honest people I know.`,
    rightAnswer: 'Present',
    specialForm: 'wears',
  },
  {
    verb: 'wear',
    sentence: `The kids {verb} Halloween costumes when they went trick or treating.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'wear',
    sentence: `My best friend has never {verb} high heels before. She prefers sneakers and trainers.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'weave',
    sentence: `These women in Bolivia {verb} carpets for a living.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'weave',
    sentence: `My grandmother {verb} baskets. Would you like to see them?`,
    rightAnswer: 'Present',
    specialForm: 'weaves',
  },
  {
    verb: 'weave',
    sentence: `Back in the days, people used to spin their own yarn from sheep wool. With the yarn, they {verb} their own clothes.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'weave',
    sentence: `The fabric is {verb} on these huge weaving machines.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'weep',
    sentence: `Try to {verb}; nothing gives such relief as tears.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'weep',
    sentence: `My brother {verb} like a baby when he loses a game.`,
    rightAnswer: 'Present',
    specialForm: 'weeps',
  },
  {
    verb: 'weep',
    sentence: `The baby boy {verb} himself to sleep last night.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'win',
    sentence: `If they {verb} the championship, they will have a big party.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'win',
    sentence: `Real Madrid often {verb}.`,
    rightAnswer: 'Present',
    specialForm: 'wins',
  },
  {
    verb: 'win',
    sentence: `He {verb} the 400-meter race last year.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'win',
    sentence: `Angelina Jolie hasn't {verb} any awards before.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'wind',
    sentence: `Every now and then we have to {verb} the clock.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wind',
    sentence: `The trail {verb} through the trees all the way up the mountain.`,
    rightAnswer: 'Present',
    specialForm: 'winds',
  },
  {
    verb: 'wind',
    sentence: `There was a cold wind, so I {verb} a scarf around my neck.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'wind',
    sentence: `The nurse has {verb} my arm with a bandage.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'withdraw',
    sentence: `Many people use ATMs to {verb} money.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'withdraw',
    sentence: `His grandmother {verb} €50 from the bank every week.`,
    rightAnswer: 'Present',
    specialForm: 'withdraws',
  },
  {
    verb: 'withdraw',
    sentence: `Yesterday I {verb} €250 from my bank account.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'withdraw',
    sentence: `All my money has been {verb} from my bank account.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'wring',
    sentence: `Don't {verb} my linnen shirt; just lay it flat to dry so it won't get all wrinkled.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'wring',
    sentence: `My mother always {verb} out the wet laundry before she hangs it up to dry.`,
    rightAnswer: 'Present',
    specialForm: 'wrings',
  },
  {
    verb: 'wring',
    sentence: `My dad {verb} out the soaking wet towel and hung it up to dry.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'wring',
    sentence: `Have you {verb} out the T-shirt? It's still soaking wet.`,
    rightAnswer: 'Participle',
  },
  {
    verb: 'write',
    sentence: `I {verb} in my diary every night before I go to sleep.`,
    rightAnswer: 'Present',
  },
  {
    verb: 'write',
    sentence: `Thomas still {verb} love letters to his wife every day. He's such a romantic.`,
    rightAnswer: 'Present',
    specialForm: 'writes',
  },
  {
    verb: 'write',
    sentence: `Janet {verb} her name and address on the form and handed it to the police.`,
    rightAnswer: 'Past',
  },
  {
    verb: 'write',
    sentence: `The Harry Potter books were {verb} by J.K. Rowling.`,
    rightAnswer: 'Participle',
  },
];
