export const defaultFullVerbs = [
  {
    infinitive: 'arise',
    past: 'arose',
    participle: 'arisen',
    translation: 'surgir',
  },
  {
    infinitive: 'awake',
    past: 'awoke',
    participle: 'awoken',
    translation: 'despertar(se)',
  },
  {
    infinitive: 'be',
    past: 'was/were',
    participle: 'been',
    translation: 'ser, estar',
  },
  {
    infinitive: 'bear',
    past: 'bore',
    participle: 'borne',
    translation: 'soportar',
  },
  {
    infinitive: 'beat',
    past: 'beat',
    participle: 'beaten',
    translation: 'golpear / ganar a alguien',
  },
  {
    infinitive: 'become',
    past: 'became',
    participle: 'become',
    translation: 'convertirse en',
  },
  {
    infinitive: 'begin',
    past: 'began',
    participle: 'begun',
    translation: 'empezar',
  },
  {
    infinitive: 'bend',
    past: 'bent',
    participle: 'bent',
    translation: 'doblar(se)',
  },
  {
    infinitive: 'bet',
    past: 'bet',
    participle: 'bet',
    translation: 'apostar',
  },
  {
    infinitive: 'bid',
    past: 'bid',
    participle: 'bid',
    translation: 'pujar',
  },
  {
    infinitive: 'bind',
    past: 'bound',
    participle: 'bound',
    translation: 'encuadernar',
  },
  {
    infinitive: 'bite',
    past: 'bit',
    participle: 'bitten',
    translation: 'morder',
  },
  {
    infinitive: 'bleed',
    past: 'bled',
    participle: 'bled',
    translation: 'sangrar',
  },
  {
    infinitive: 'blow',
    past: 'blew',
    participle: 'blown',
    translation: 'soplar',
  },
  {
    infinitive: 'break',
    past: 'broke',
    participle: 'broken',
    translation: 'romper',
  },
  {
    infinitive: 'breed',
    past: 'bred',
    participle: 'bred',
    translation: 'criar',
  },
  {
    infinitive: 'bring',
    past: 'brought',
    participle: 'brought',
    translation: 'traer',
  },
  {
    infinitive: 'build',
    past: 'built',
    participle: 'built',
    translation: 'construir',
  },
  {
    infinitive: 'burn',
    past: 'burnt',
    participle: 'burnt',
    translation: 'quemar(se)',
  },
  {
    infinitive: 'burst',
    past: 'burst',
    participle: 'burst',
    translation: 'estallar',
  },
  {
    infinitive: 'buy',
    past: 'bought',
    participle: 'bought',
    translation: 'comprar',
  },
  {
    infinitive: 'cast',
    past: 'cast',
    participle: 'cast',
    translation: 'tirar',
  },
  {
    infinitive: 'catch',
    past: 'caught',
    participle: 'caught',
    translation: 'coger',
  },
  {
    infinitive: 'choose',
    past: 'chose',
    participle: 'chosen',
    translation: 'elegir',
  },
  {
    infinitive: 'cling',
    past: 'clung',
    participle: 'clung',
    translation: 'aferrarse',
  },
  {
    infinitive: 'come',
    past: 'came',
    participle: 'come',
    translation: 'venir',
  },
  {
    infinitive: 'cost',
    past: 'cost',
    participle: 'cost',
    translation: 'costar',
  },
  {
    infinitive: 'creep',
    past: 'crept',
    participle: 'crept',
    translation: 'arrastrar',
  },
  {
    infinitive: 'cut',
    past: 'cut',
    participle: 'cut',
    translation: 'cortar',
  },
  {
    infinitive: 'deal',
    past: 'dealt',
    participle: 'dealt',
    translation: 'tratar',
  },
  {
    infinitive: 'dig',
    past: 'dug',
    participle: 'dug',
    translation: 'cavar',
  },
  {
    infinitive: 'do',
    past: 'did',
    participle: 'done',
    translation: 'hacer',
  },
  {
    infinitive: 'draw',
    past: 'drew',
    participle: 'drawn',
    translation: 'dibujar',
  },
  {
    infinitive: 'dream',
    past: 'dreamt',
    participle: 'dreamt',
    translation: 'soñar',
  },
  {
    infinitive: 'drink',
    past: 'drank',
    participle: 'drunk',
    translation: 'beber',
  },
  {
    infinitive: 'drive',
    past: 'drove',
    participle: 'driven',
    translation: 'conducir',
  },
  {
    infinitive: 'eat',
    past: 'ate',
    participle: 'eaten',
    translation: 'comer',
  },
  {
    infinitive: 'fall',
    past: 'fell',
    participle: 'fallen',
    translation: 'caer(se)',
  },
  {
    infinitive: 'feed',
    past: 'fed',
    participle: 'fed',
    translation: 'alimentar',
  },
  {
    infinitive: 'feel',
    past: 'felt',
    participle: 'felt',
    translation: 'sentirse',
  },
  {
    infinitive: 'fight',
    past: 'fought',
    participle: 'fought',
    translation: 'pelearse',
  },
  {
    infinitive: 'find',
    past: 'found',
    participle: 'found',
    translation: 'encontrar',
  },
  {
    infinitive: 'flee',
    past: 'fled',
    participle: 'fled',
    translation: 'huir',
  },
  {
    infinitive: 'fly',
    past: 'flew',
    participle: 'flown',
    translation: 'volar',
  },
  {
    infinitive: 'forbid',
    past: 'forbade',
    participle: 'forbidden',
    translation: 'prohibir',
  },
  {
    infinitive: 'forget',
    past: 'forgot',
    participle: 'forgotten',
    translation: 'olvidar(se)',
  },
  {
    infinitive: 'forgive',
    past: 'forgave',
    participle: 'forgiven',
    translation: 'perdonar',
  },
  {
    infinitive: 'freeze',
    past: 'froze',
    participle: 'frozen',
    translation: 'helar(se)',
  },
  {
    infinitive: 'get',
    past: 'got',
    participle: 'got',
    translation: 'conseguir',
  },
  {
    infinitive: 'give',
    past: 'gave',
    participle: 'given',
    translation: 'dar',
  },
  {
    infinitive: 'go',
    past: 'went',
    participle: 'gone',
    translation: 'irse',
  },
  {
    infinitive: 'grind',
    past: 'ground',
    participle: 'ground',
    translation: 'moler',
  },
  {
    infinitive: 'grow',
    past: 'grew',
    participle: 'grown',
    translation: 'crecer',
  },
  {
    infinitive: 'hang',
    past: 'hung',
    participle: 'hung',
    translation: 'colgar',
  },
  {
    infinitive: 'have',
    past: 'had',
    participle: 'had',
    translation: 'haber, tener',
  },
  {
    infinitive: 'hear',
    past: 'heard',
    participle: 'heard',
    translation: 'escuchar',
  },
  {
    infinitive: 'hide',
    past: 'hid',
    participle: 'hidden',
    translation: 'esconder(se)',
  },
  {
    infinitive: 'hit',
    past: 'hit',
    participle: 'hit',
    translation: 'pegar',
  },
  {
    infinitive: 'hold',
    past: 'held',
    participle: 'held',
    translation: 'agarrar(se)',
  },
  {
    infinitive: 'hurt',
    past: 'hurt',
    participle: 'hurt',
    translation: 'hacer daño',
  },
  {
    infinitive: 'keep',
    past: 'kept',
    participle: 'kept',
    translation: 'guardar',
  },
  {
    infinitive: 'kneel',
    past: 'knelt',
    participle: 'knelt',
    translation: 'arrodillarse',
  },
  {
    infinitive: 'know',
    past: 'knew',
    participle: 'known',
    translation: 'saber, conocer',
  },
  {
    infinitive: 'lay',
    past: 'laid',
    participle: 'laid',
    translation: 'poner',
  },
  {
    infinitive: 'lead',
    past: 'led',
    participle: 'led',
    translation: 'dirigir',
  },
  {
    infinitive: 'lean',
    past: 'leant',
    participle: 'leant',
    translation: 'apoyarse',
  },
  {
    infinitive: 'leap',
    past: 'leapt',
    participle: 'leapt',
    translation: 'brincar',
  },
  {
    infinitive: 'learn',
    past: 'learnt',
    participle: 'learnt',
    translation: 'aprender',
  },
  {
    infinitive: 'leave',
    past: 'left',
    participle: 'left',
    translation: 'dejar',
  },
  {
    infinitive: 'lend',
    past: 'lent',
    participle: 'lent',
    translation: 'prestar',
  },
  {
    infinitive: 'let',
    past: 'let',
    participle: 'let',
    translation: 'permitir',
  },
  {
    infinitive: 'lie',
    past: 'lay',
    participle: 'lain',
    translation: 'echarse',
  },
  {
    infinitive: 'light',
    past: 'lit',
    participle: 'lit',
    translation: 'encender(se)',
  },
  {
    infinitive: 'lose',
    past: 'lost',
    participle: 'lost',
    translation: 'perder',
  },
  {
    infinitive: 'make',
    past: 'made',
    participle: 'made',
    translation: 'hacer',
  },
  {
    infinitive: 'mean',
    past: 'meant',
    participle: 'meant',
    translation: 'significar',
  },
  {
    infinitive: 'meet',
    past: 'met',
    participle: 'met',
    translation: 'encontrar(se)',
  },
  {
    infinitive: 'overcome',
    past: 'overcame',
    participle: 'overcome',
    translation: 'vencer',
  },
  {
    infinitive: 'pay',
    past: 'paid',
    participle: 'paid',
    translation: 'pagar',
  },
  {
    infinitive: 'put',
    past: 'put',
    participle: 'put',
    translation: 'poner',
  },
  {
    infinitive: 'read',
    past: 'read',
    participle: 'read',
    translation: 'leer',
  },
  {
    infinitive: 'ride',
    past: 'rode',
    participle: 'ridden',
    translation: 'montar',
  },
  {
    infinitive: 'ring',
    past: 'rang',
    participle: 'rung',
    translation: 'sonar',
  },
  {
    infinitive: 'rise',
    past: 'rose',
    participle: 'risen',
    translation: 'levantarse',
  },
  {
    infinitive: 'run',
    past: 'ran',
    participle: 'run',
    translation: 'correr',
  },
  {
    infinitive: 'saw',
    past: 'sawed',
    participle: 'sawn',
    translation: 'serrar',
  },
  {
    infinitive: 'say',
    past: 'said',
    participle: 'said',
    translation: 'decir',
  },
  {
    infinitive: 'see',
    past: 'saw',
    participle: 'seen',
    translation: 'ver',
  },
  {
    infinitive: 'seek',
    past: 'sought',
    participle: 'sought',
    translation: 'buscar',
  },
  {
    infinitive: 'sell',
    past: 'sold',
    participle: 'sold',
    translation: 'vender(se)',
  },
  {
    infinitive: 'send',
    past: 'sent',
    participle: 'sent',
    translation: 'enviar',
  },
  {
    infinitive: 'set',
    past: 'set',
    participle: 'set',
    translation: 'poner',
  },
  {
    infinitive: 'sew',
    past: 'sewed',
    participle: 'sewn',
    translation: 'coser',
  },
  {
    infinitive: 'shake',
    past: 'shook',
    participle: 'shaken',
    translation: 'agitar',
  },
  {
    infinitive: 'shear',
    past: 'sheared',
    participle: 'shorn',
    translation: 'esquilar',
  },
  {
    infinitive: 'shine',
    past: 'shone',
    participle: 'shone',
    translation: 'brillar',
  },
  {
    infinitive: 'shoot',
    past: 'shot',
    participle: 'shot',
    translation: 'disparar',
  },
  {
    infinitive: 'show',
    past: 'showed',
    participle: 'shown',
    translation: 'mostrar',
  },
  {
    infinitive: 'shrink',
    past: 'shrank',
    participle: 'shrunk',
    translation: 'encoger(se)',
  },
  {
    infinitive: 'shut',
    past: 'shut',
    participle: 'shut',
    translation: 'cerrar(se)',
  },
  {
    infinitive: 'sing',
    past: 'sang',
    participle: 'sung',
    translation: 'cantar',
  },
  {
    infinitive: 'sink',
    past: 'sank',
    participle: 'sunk',
    translation: 'hundir(se)',
  },
  {
    infinitive: 'sit',
    past: 'sat',
    participle: 'sat',
    translation: 'sentar(se)',
  },
  {
    infinitive: 'sleep',
    past: 'slept',
    participle: 'slept',
    translation: 'dormir',
  },
  {
    infinitive: 'slide',
    past: 'slid',
    participle: 'slid',
    translation: 'resbalar',
  },
  {
    infinitive: 'smell',
    past: 'smelt',
    participle: 'smelt',
    translation: 'oler',
  },
  {
    infinitive: 'sow',
    past: 'sowed',
    participle: 'sown',
    translation: 'sembrar',
  },
  {
    infinitive: 'speak',
    past: 'spoke',
    participle: 'spoken',
    translation: 'hablar',
  },
  {
    infinitive: 'speed',
    past: 'sped',
    participle: 'sped',
    translation: 'acelerar',
  },
  {
    infinitive: 'spell',
    past: 'spelt',
    participle: 'spelt',
    translation: 'deletrear',
  },
  {
    infinitive: 'spend',
    past: 'spent',
    participle: 'spent',
    translation: 'pagar, gastar',
  },
  {
    infinitive: 'spill',
    past: 'spilt',
    participle: 'spilt',
    translation: 'derramar',
  },
  {
    infinitive: 'spit',
    past: 'spat',
    participle: 'spat',
    translation: 'escupir',
  },
  {
    infinitive: 'split',
    past: 'split',
    participle: 'split',
    translation: 'dividir, partir',
  },
  {
    infinitive: 'spoil',
    past: 'spoilt',
    participle: 'spoilt',
    translation: 'estropear(se)',
  },
  {
    infinitive: 'spread',
    past: 'spread',
    participle: 'spread',
    translation: 'extender(se)',
  },
  {
    infinitive: 'stand',
    past: 'stood',
    participle: 'stood',
    translation: 'estar de pie',
  },
  {
    infinitive: 'steal',
    past: 'stole',
    participle: 'stolen',
    translation: 'robar',
  },
  {
    infinitive: 'stick',
    past: 'stuck',
    participle: 'stuck',
    translation: 'pegar(se)',
  },
  {
    infinitive: 'sting',
    past: 'stung',
    participle: 'stung',
    translation: 'picar',
  },
  {
    infinitive: 'stink',
    past: 'stank',
    participle: 'stunk',
    translation: 'apestar',
  },
  {
    infinitive: 'strike',
    past: 'struck',
    participle: 'struck',
    translation: 'golpear',
  },
  {
    infinitive: 'strive',
    past: 'strove',
    participle: 'striven',
    translation: 'esforzarse',
  },
  {
    infinitive: 'swear',
    past: 'swore',
    participle: 'sworn',
    translation: 'jurar',
  },
  {
    infinitive: 'sweep',
    past: 'swept',
    participle: 'swept',
    translation: 'barrer',
  },
  {
    infinitive: 'swim',
    past: 'swam',
    participle: 'swum',
    translation: 'nadar',
  },
  {
    infinitive: 'swing',
    past: 'swung',
    participle: 'swung',
    translation: 'balancear(se)',
  },
  {
    infinitive: 'take',
    past: 'took',
    participle: 'taken',
    translation: 'tomar(se)',
  },
  {
    infinitive: 'teach',
    past: 'taught',
    participle: 'taught',
    translation: 'enseñar',
  },
  {
    infinitive: 'tear',
    past: 'tore',
    participle: 'torn',
    translation: 'romper(se)',
  },
  {
    infinitive: 'tell',
    past: 'told',
    participle: 'told',
    translation: 'contar, decir',
  },
  {
    infinitive: 'think',
    past: 'thought',
    participle: 'thought',
    translation: 'pensar',
  },
  {
    infinitive: 'throw',
    past: 'threw',
    participle: 'thrown',
    translation: 'lanzar',
  },
  {
    infinitive: 'tread',
    past: 'trod',
    participle: 'trodden',
    translation: 'pisar',
  },
  {
    infinitive: 'undergo',
    past: 'underwent',
    participle: 'undergone',
    translation: 'someterse a, experimentar',
  },
  {
    infinitive: 'understand',
    past: 'understood',
    participle: 'understood',
    translation: 'entender',
  },
  {
    infinitive: 'upset',
    past: 'upset',
    participle: 'upset',
    translation: 'afligir',
  },
  {
    infinitive: 'wake up',
    past: 'woke up',
    participle: 'woken up',
    translation: 'despertar(se)',
  },
  {
    infinitive: 'wear',
    past: 'wore',
    participle: 'worn',
    translation: 'llevar (puesto)',
  },
  {
    infinitive: 'weave',
    past: 'wove',
    participle: 'woven',
    translation: 'tejer',
  },
  {
    infinitive: 'weep',
    past: 'wept',
    participle: 'wept',
    translation: 'llorar',
  },
  {
    infinitive: 'win',
    past: 'won',
    participle: 'won',
    translation: 'ganar',
  },
  {
    infinitive: 'wind',
    past: 'wound',
    participle: 'wound',
    translation: 'enrollar',
  },
  {
    infinitive: 'withdraw',
    past: 'withdrew',
    participle: 'withdrawn',
    translation: 'retirar(se)',
  },
  {
    infinitive: 'wring',
    past: 'wrung',
    participle: 'wrung',
    translation: 'escurrir',
  },
  {
    infinitive: 'write',
    past: 'wrote',
    participle: 'written',
    translation: 'escribir',
  },
];

export const defaultSelectedVerbs = [
  'arise',
  'awake',
  'be',
  'bear',
  'beat',
  'become',
  'begin',
  'bend',
  'bet',
  'bid',
  'bind',
  'bite',
  'bleed',
  'blow',
  'break',
  'breed',
  'bring',
  'build',
  'burn',
  'burst',
  'buy',
  'cast',
  'catch',
  'choose',
  'cling',
  'come',
  'cost',
  'creep',
  'cut',
  'deal',
  'dig',
  'do',
  'draw',
  'dream',
  'drink',
  'drive',
  'eat',
  'fall',
  'feed',
  'feel',
  'fight',
  'find',
  'flee',
  'fly',
  'forbid',
  'forget',
  'forgive',
  'freeze',
  'get',
  'give',
  'go',
  'grind',
  'grow',
  'hang',
  'have',
  'hear',
  'hide',
  'hit',
  'hold',
  'hurt',
  'keep',
  'kneel',
  'know',
  'lay',
  'lead',
  'lean',
  'leap',
  'learn',
  'leave',
  'lend',
  'let',
  'lie',
  'light',
  'lose',
  'make',
  'mean',
  'meet',
  'overcome',
  'pay',
  'put',
  'read',
  'ride',
  'ring',
  'rise',
  'run',
  'saw',
  'say',
  'see',
  'seek',
  'sell',
  'send',
  'set',
  'sew',
  'shake',
  'shear',
  'shine',
  'shoot',
  'show',
  'shrink',
  'shut',
  'sing',
  'sink',
  'sit',
  'sleep',
  'slide',
  'smell',
  'sow',
  'speak',
  'speed',
  'spell',
  'spend',
  'spill',
  'spit',
  'split',
  'spoil',
  'spread',
  'stand',
  'steal',
  'stick',
  'sting',
  'stink',
  'strike',
  'strive',
  'swear',
  'sweep',
  'swim',
  'swing',
  'take',
  'teach',
  'tear',
  'tell',
  'think',
  'throw',
  'tread',
  'undergo',
  'understand',
  'upset',
  'wake up',
  'wear',
  'weave',
  'weep',
  'win',
  'wind',
  'withdraw',
  'wring',
  'write',
];
