name: Production CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/lemoncode/english-quiz:prod-${{github.sha}}-${{github.run_attempt}}

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  cd:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://englishquiz.fun
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker build \
          -t ${{env.IMAGE_NAME}} \
          .
          docker push ${{env.IMAGE_NAME}}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{env.IMAGE_NAME}}
