name: Production CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  IMAGE_NAME: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

jobs:
  cd:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://englishquiz.fun
    steps:
      - uses: actions/checkout@v2

      - name: Install heroku and login
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login

      - name: Build docker image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Deploy docker image
        run: docker push ${{env.IMAGE_NAME}}

      - name: Release
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
