name: Continuous Deployment Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
