name: Development CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  IMAGE_NAME: ${{secrets.AWS_DOCKER_REGISTRY}}/english-quiz:dev-${GITHUB_RUN_ID}-${GITHUB_SHA}-${GITHUB_RUN_ATTEMPT}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}} .
          docker push ${{env.IMAGE_NAME}}

  deploy:
    needs: [build-image]
    uses: lemoncode/actions/.github/workflows/aws-ec2-docker-deploy.yml@develop
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
      AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_EC2_INSTANCE_ID: ${{secrets.DEV_AWS_EC2_INSTANCE_ID}}
      DOCKER_IMAGE_NAME: ${{secrets.AWS_DOCKER_REGISTRY}}/english-quiz:dev-${GITHUB_RUN_ID}-${GITHUB_SHA}-${GITHUB_RUN_ATTEMPT}
      DOCKER_RUN_PARAMS: '-p 127.0.0.1:3000:3000'
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}

  configure-https:
    needs: [deploy]
    uses: lemoncode/actions/.github/workflows/aws-ec2-configure-https.yml@develop
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
      AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_EC2_INSTANCE_ID: ${{secrets.DEV_AWS_EC2_INSTANCE_ID}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}
      DOMAIN_RECORD_NAME: ${{secrets.DEV_AWS_DOMAIN_RECORD_NAME}}
      EMAIL: ${{secrets.CERT_EMAIL}}
