name: Initialize dev server configuration

on:
  workflow_dispatch:

jobs:
  configure-server-to-dispatch-github-events:
    uses: lemoncode/actions/.github/workflows/aws-ec2-allow-dispatch-github-event.yml@develop
    with:
      dispatch-event: dev-update-dns-record
      organization: lemoncode
      repository: english-quiz
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
      AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_EC2_INSTANCE_ID: ${{secrets.DEV_AWS_EC2_INSTANCE_ID}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}
      TOKEN_TO_DISPATCH_EVENT: ${{secrets.TOKEN_TO_DISPATCH_EVENT}}

  install-docker-on-server:
    uses: lemoncode/actions/.github/workflows/aws-ec2-install-docker.yml@develop
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
      AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_EC2_INSTANCE_ID: ${{secrets.DEV_AWS_EC2_INSTANCE_ID}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}
