name: Development CD

on:
  push:
    branches:
      - develop

jobs:
  dev-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}
      - name: Connect to EC2 instance
        run: |
          echo "${{secrets.SSH_KEY}}" > private-key
          sudo chmod 600 private-key
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{secrets.DEV_AWS_EC2_INSTANCE_ID}} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          scp -o StrictHostKeyChecking=no -i private-key ./dispatch-update-route53.sh ${{secrets.SSH_USER}}@$PUBLIC_IP:~/dispatch-update-route53.sh
          ssh -o StrictHostKeyChecking=no -i private-key ${{secrets.SSH_USER}}@$PUBLIC_IP "

          EVENT=${{secrets.DEV_DISPATCH_EVENT}}
          GITHUB_TOKEN=${{secrets.DEV_DISPATCH_TOKEN}}
          ORGANIZATION=${{secrets.DEV_DISPATCH_ORGANIZATION}}
          REPOSITORY=${{secrets.DEV_DISPATCH_REPOSITORY}}

          sudo cp ~/dispatch-update-route53.sh /var/lib/cloud/scripts/per-boot/dispatch-update-route53.sh
          sudo chmod 744 /var/lib/cloud/scripts/per-boot/dispatch-update-route53.sh
          sudo rm ~/dispatch-update-route53.sh
          exit
          "

